### ISSUE TITLE
User "admin" cannot list componentstatuses at the cluster scope

### ISSUE THREAD

**Issue by kyrias** [kelseyhightower/kubernetes-the-hard-way#197]
I'm currently on 07-kubectl.md, and the `kubectl get componentstatuses` returns the following error when trying to run it on my local machine:

```
Error from server (Forbidden): User "admin" cannot list componentstatuses at the cluster scope. (get componentstatuses)
```

I'm pretty sure I've run all the commands from the previous labs, so I'm not sure what could be wrong.

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.

**Comment by mattjmcnaughton** [comment]
I'm unfortunately still getting the same error - despite using [10-kubectl.md](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/10-configuring-kubectl.md), i.e. the updated docs. Any help would be greatly appreciated.

thanks for your work on this awesome project @kelseyhightower :)

**Comment by tkellen** [comment]
For future readers, the admin user needs to be bound to the clusterrole `cluster-admin`. You can accomplish that by running this on one of the controllers:
```
kubectl create clusterrolebinding root-cluster-admin-binding --clusterrole=cluster-admin --user=admin
```

**Comment by tkellen** [comment]
...or you need to ensure that the csr you make for the admin user has the organization `system:masters`:

see: https://kubernetes.io/docs/admin/authorization/rbac/#user-facing-roles

**Comment by bigknife** [comment]
> For future readers, the admin user needs to be bound to the clusterrole `cluster-admin`. You can accomplish that by running this on one of the controllers:
> 
> ```
> kubectl create clusterrolebinding root-cluster-admin-binding --clusterrole=cluster-admin --user=admin
> ```

Thanks. 
I did remove ~/.kube, and 
```
kubectl create clusterrolebinding root-cluster-admin-binding --clusterrole=cluster-admin --user=admin
```

after use the new context, it works.
